### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Zesame"

### ISSUE THREAD

**Issue by AlleniCode** [OpenZesame/Zesame#41]
My pod platform is ios, '8.0', when I install Zesame:

[!] CocoaPods could not find compatible versions for pod "Zesame":
  In Podfile:
    Zesame (from `https://github.com/OpenZesame/Zesame.git`, branch `master`)

Specs satisfying the `Zesame (from `https://github.com/OpenZesame/Zesame.git`, branch `master`)` dependency were found, but they required a higher minimum deployment target.

The Zesame only support iOS 11.0+ ?

**Comment by Sajjon** [comment]
Yes, iOS 11.0 and above. [95% of all iOS devices in the world run iOS 11.0+](https://developer.apple.com/support/app-store/), so why would you want to support lower versions?
